# usage:
# to download from arxiv make sure .s3cfg file is present (see Dockerfile)
# sudo docker-compose -f dev_docker-compose.yml run web


version: '3'

services:
  web:
    build: .
    volumes:
      - .:/code
